### PR TITLE
hello-world: update to ease comprehension

### PR DESCRIPTION
**Pull request by rpottsoh**
Being the first exercise I thought it important to illustrate for the student what are the params of Assert.AreEqual.

### CODE REVIEW

**Comment by rpottsoh** [comment]
Will do, thanks.


Sent from my android device.

**Comment by rpottsoh** [comment]
@kotp I have inserted some comments.  Not sure if it is sufficient.  Is hard for me to judge.

**Comment by rpottsoh** [comment]
:+1:   Thanks

**Comment by kotp** [comment]
I think it is good.

**Pull request merged**
