### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by rpottsoh**
File is empty so expecting default behavior for probot/stale.

### CODE REVIEW

**Comment by rpottsoh** [comment]
@kotp, do we need this?

**Comment by kotp** [comment]
If it were populated with at least the defaults... But if everything is acceptable as the defaults, then I would say "no".

**Comment by rpottsoh** [comment]
I think robot is not active unless the file exists in the repo.  If we don't want the robot to be active then we should omit the file. Empty file = default behavior. 


Sent from my android device.

**Comment by kotp** [comment]
Yes, the "Yes we do" is not fully communicative.  We need it if we want the probot enhancement.

I think that we should have it... ...

**Pull request merged**
