### PR TITLE
phone-number: update to match canonical-data.json

### PR DESCRIPTION
**Pull request by rpottsoh**
Canonical-data.json recently changed.  Updating test runner and example solution to align with new json.

### CODE REVIEW

**Comment by kotp** [comment]
This may need to be mentioned in x-common repository, but the tests for invalid_when_11 and valid_when_11 seem contradictory, if only due to lack of message in the test.  Is there a way to have a custom message reported giving the reason why 11 is invalid, sometimes?

**Comment by rpottsoh** [comment]
Of course a message can be displayed, however it is only displayed on a failure.  Is that what you are after?

Sent from my android device.

**Comment by rpottsoh** [comment]
@kotp instead of `"invalid when 11 digits"` how about `"invalid when not starting with 1 and is 11 digits"`?  This would then seem to be balanced by `"valid when 11 digits and starting with 1"`.  If this seems reasonable I'll open an issue, or should I just submit a PR for the change?

**Comment by kotp** [comment]
You can make the change here, and potentially create that issue (or even a PR with the change) on x-common.

**Comment by kotp** [comment]
If you only make the change here, then when we do the generator we would still have the same issue potentially.

**Comment by rpottsoh** [comment]
@kotp `invalid when 11 digits` is now `invalid when 11 digits not starting with 1`.  Slightly different wording from earlier.  OK?  If you're OK with it I'll open a PR in x-common to propose a change to the canonical-data.json.  Would I need to bump the version, to what?

**Comment by kotp** [comment]
"invalid when 11 digits does not start with a 1"

**Comment by rpottsoh** [comment]
I'll update this PR after https://github.com/exercism/x-common/pull/724 in x-common shakes out.

**Comment by rpottsoh** [comment]
@kotp, [canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/phone-number/canonical-data.json) has been updated.  I have updated my 2nd commit to reflect the change to the json description...  Should the two commits be squashed or merged as is?

**Comment by kotp** [comment]
Yes, no point in bringing in the change if it isn't up to date.

**Pull request merged**
